services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk_soar
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - "8000:8000" # Splunk Web UI
      - "8088:8088" # HTTP Event Collector (HEC)
      - "8089:8089" # Splunk REST API
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-etc:
  splunk-var: